---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    name: whoami-mirror
    namespace: app
spec:
  entryPoints:
     - websecure
  routes:
    - kind: Rule
      match: Host(`m.waw.demo.traefiklabs.tech`)
      services:
        - kind: TraefikService 
          name: mirror-whoami
          namespace: app
  tls:
    certResolver: le           